### ISSUE TITLE
Some different results

### ISSUE THREAD

**Issue by HanNight** [tommccoy1/hans#4]
I trained a BERT on MNLI, and evaluated it on HANS dataset. However, I got the results different from the results in your paper.

| Model | Lexical(en) | Subseq(en) | Const(en) | Lexical(non-en) | Subseq(non-en) | Const(non-en) |
| ----- | ----------- | ---------- | --------- | -------------- | ------------- | ------------ |
| BERT(yours) | 0.95 | 0.99 | 0.98 | 0.16 | 0.04 | 0.16 |
| BERT(mine) | 0.99 | 1.00 | 1.00 | 0.52 | 0.04 | 0.19 |

Why my acc in lexical(non-entailment) is much higher than yours?

**Comment by tommccoy1** [comment]
It turns out that, across different random re-runs of fine-tuning, BERT has considerable variability on the lexical non-entailment cases. We have just uploaded a follow-up to the HANS paper documenting this variability across 100 re-runs:
https://arxiv.org/abs/1911.02969
In short, on the lexical non-entailment case, we found that accuracy ranged from 6% to 54% - so the result you got of 52% is within the range of variation that we found (albeit near the top of that range).

**Comment by HanNight** [comment]
Thanks
